[tool.black]
line-length = 99 # override black's default line-length

[tool.isort]
# make it compatible with black
profile = "black"

[tool.pyright]
reportUnknownMemberType = "none"
reportUnknownArgumentType = "none"
reportUnknownParameterType = "none"
reportUnknownVariableType = "none"
reportPrivateImportUsage = "none"
reportMissingTypeStubs = false
